### ISSUE TITLE
App keeps Loading indefinitely. 

### ISSUE THREAD

**Issue by emzero** [waldekmastykarz/office-mygroups-react#1]
I've followed all the steps. App prompt me to login. Redirect URI matched and it redirects back to the page with "My groups" title but then it stays Loading for ever.

DevTools doesn't seem to show any XHR request.

Will investigate a little more but any help is appreciated.

**Comment by waldekmastykarz** [comment]
Could you please double check the return URL and that you granted all permissions?

**Comment by emzero** [comment]
![image](https://cloud.githubusercontent.com/assets/412489/17981876/eb7ebac0-6adb-11e6-916a-8f158ddd62d6.png)

Reply URL is indeed **https://localhost:8443** (it's not called Return URL).
App has all the permissions available to Office 365 Management APIs, Microsoft Graph and Windows Azure Active Directory.

Not sure where to check for "in application's manifest enable OAuth implicit flow"

**Comment by emzero** [comment]
`_adal.acquireToken()` is throwing the following error:
```
"AADSTS70005: response_type 'token' is not enabled for the application
Trace ID: 7f216c1b-cf65-4654-87d3-5b156c702e0f
Correlation ID: 33d8c4cd-e06f-4df5-8f1d-95b4f34a69d4
Timestamp: 2016-08-25 17:00:33Z"
```

I guess that's related to the OAuth implicit flow?

**Comment by emzero** [comment]
I've found the "manage manifest" option in Azure, downloaded it, changed the `  oauth2AllowImplicitFlow` key to `true`, uploaded it. Same error.

**Comment by emzero** [comment]
Ok, had to logout and login back again. Now it's working.
Thanks!

**Comment by waldekmastykarz** [comment]
Glad to hear it's working and you've figured it out. Thanks for reaching out!
